version: "3"
services:

  postgres:
    container_name: postgres-11
    image: postgres:11
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  backend:
    container_name: viruscheckapp-backend
    restart: always
    build: backend/.
    ports:
      - "8000:80"
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres

  app:
    container_name: viruscheckapp-app
    restart: always
    build: frontend/.
    ports:
      - "80:3000"
    depends_on:
      - backend

  pgadmin:
    container_name: pgadmin-4
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "5050:80"
    depends_on:
      - postgres
