version: "3"
services:

  postgres:
    container_name: postgres-latest
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  backend:
    container_name: viruscheckapp-backend
    restart: always
    build: backend/.
    ports:
      - "8000:80"
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres

  app:
    container_name: viruscheckapp-app
    restart: always
    build: frontend/.
    ports:
      - "80:3000"
    depends_on:
      - backend
